export type View = 'gpu' | 'sm'
export type DistrictId = 'host' | 'dispatch' | 'copy' | 'dram' | 'l2' | 'sm' | 'scheduler' | 'registers' | 'shared' | 'cuda' | 'tensor' | 'rt'

export const SOURCES = {
  rtx: 'https://www.nvidia.com/en-gb/geforce/rtx/',
  toolkit: 'https://developer.nvidia.com/cuda/toolkit',
  model: 'https://docs.nvidia.com/cuda/cuda-programming-guide/01-introduction/programming-model.html',
  ada: 'https://docs.nvidia.com/cuda/ada-tuning-guide/index.html',
  occupancy: 'https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html#occupancy',
} as const

export interface District {
  id: DistrictId
  name: string
  subtitle: string
  view: View
  color: string
  description: string
  facts: [string, string][]
  boundary: string
  source: string
}

export const DISTRICTS: District[] = [
  { id: 'host', name: 'Host CPU', subtitle: 'CUDA runtime / software', view: 'gpu', color: '#8bb9e7', description: 'CUDA applications start on the host. The runtime manages allocations, copies, streams, and kernel launches. The CUDA Toolkit includes compilers, libraries, and developer tools; it is not a physical part of the GPU die.', facts: [['Build time', 'nvcc / device code compilation'], ['Run time', 'Host application + CUDA runtime / driver'], ['Libraries', 'cuBLAS, cuFFT, and other CUDA libraries']], boundary: 'The city does not compile or execute CUDA. Software is shown outside the die to distinguish it from the execution hardware.', source: SOURCES.toolkit },
  { id: 'dispatch', name: 'Grid dispatch', subtitle: 'Blocks assigned to SMs', view: 'gpu', color: '#ebc76d', description: 'A kernel launch defines a grid of thread blocks. A block is assigned to one SM, where its threads form warps. Independent blocks may execute in different orders; a program must not assume a particular block-to-SM mapping.', facts: [['Execution hierarchy', 'Grid > block > warp > thread'], ['Block location', 'One SM for ordinary block execution'], ['Scheduling order', 'Not guaranteed']], boundary: 'This district represents a scheduling concept, not a claimed die floorplan or a cycle-accurate dispatch algorithm.', source: SOURCES.model },
  { id: 'copy', name: 'Host/device transfer', subtitle: 'PCIe / copy path', view: 'gpu', color: '#75d8d6', description: 'Host and device memory are distinct in this discrete-GPU view. Copies move data across an interconnect. Streams and suitable memory/copy-engine support can allow independent transfer and compute work to overlap.', facts: [['What moves', 'Data buffers, not warps'], ['Lifetime', 'Keep reusable data on the device'], ['Unified Memory', 'Addressing and migration still have costs']], boundary: 'Transfer latency, overlap, and zero-copy behavior depend on the system. None are measured or promised by this path.', source: SOURCES.model },
  { id: 'dram', name: 'Device DRAM', subtitle: 'Global memory / VRAM', view: 'gpu', color: '#74cbdc', description: 'Device DRAM stores global arrays, model weights, and outputs. The L2 and per-SM caches mediate many accesses. Global memory is not the same resource as an SM-local shared-memory allocation.', facts: [['Scope', 'Device-wide global address space'], ['Data examples', 'Inputs, weights, output arrays'], ['Traffic', 'Loads and stores / cache reuse']], boundary: 'The displayed memory banks and chip count are schematic. No SKU capacity, bandwidth, or latency is claimed.', source: SOURCES.model },
  { id: 'l2', name: 'L2 cache', subtitle: 'Shared across SMs', view: 'gpu', color: '#67b9dd', description: 'L2 sits between the SMs and device memory and can reuse data across SM requests. It is distinct from each SM\'s L1/shared-memory resources and from the explicit host/device copy path.', facts: [['Scope', 'Device cache shared by SMs'], ['Backing storage', 'Device DRAM'], ['Coalescing', 'Access patterns affect memory transactions']], boundary: 'Cache hit rate and bandwidth are not simulated. Colored traffic indicates a conceptual load/store path.', source: SOURCES.ada },
  { id: 'sm', name: 'SM array', subtitle: 'Eight representative SMs', view: 'gpu', color: '#a4d86b', description: 'Streaming multiprocessors execute resident warps using their schedulers, registers, local memory resources, and functional units. The array shows eight representative SMs; real GPUs contain a SKU-dependent number grouped into GPCs.', facts: [['Ada warp capacity', '48 warps per SM'], ['Warp size', '32 threads'], ['Thread-block capacity', '24 blocks per SM']], boundary: 'Eight SMs and the grouping here are diagram scale choices. The capacity model is per SM, not a specification of an entire RTX product.', source: SOURCES.ada },
  { id: 'scheduler', name: 'Warp scheduling', subtitle: 'Resident execution contexts', view: 'sm', color: '#d8d5ae', description: 'Threads in a block are grouped into warps of 32. Warp schedulers issue eligible instructions while other warps may wait on dependencies or memory. A warp is an execution context; it does not fly out to DRAM or equal one CUDA core.', facts: [['Ada capacity', '48 resident warps / SM'], ['Thread grouping', '32 lanes per warp'], ['Divergence', 'Different active lane masks may execute different paths']], boundary: 'The 48-slot display is a residency illustration, not the physical scheduler layout, instruction issue width, or cycle timing.', source: SOURCES.model },
  { id: 'registers', name: 'Register file', subtitle: 'Thread-local state', view: 'sm', color: '#a9bac4', description: 'Registers hold thread-local values. Resident blocks reserve registers for their threads, so high register use can reduce the number of blocks that fit on an SM. Register spilling goes to the local-memory address space, backed by device memory.', facts: [['Ada registers / SM', '65,536 x 32-bit registers'], ['Maximum / thread', '255 registers'], ['Total raw capacity', '256 KiB / SM']], boundary: 'The capacity bound omits hardware allocation granularity and partition constraints. Use the CUDA occupancy API or Nsight Compute for an actual compiled kernel.', source: SOURCES.ada },
  { id: 'shared', name: 'L1 / shared memory', subtitle: 'Local to one SM', view: 'sm', color: '#77cec5', description: 'Ada combines L1, texture cache, and shared-memory resources. Shared memory is explicitly allocated per block for cooperation and tile reuse; different blocks do not simply share each other\'s allocations.', facts: [['Combined capacity', '128 KiB L1 / texture / shared'], ['Shared-memory carveout', 'Up to 100 KiB / SM'], ['Block reservation', '1 KiB reserved; up to 99 KiB addressable / block']], boundary: 'This model assumes the maximum shared carveout. Dynamic allocations above 48 KiB require opt-in. Bank conflicts and carveout changes are not simulated.', source: SOURCES.ada },
  { id: 'cuda', name: 'CUDA arithmetic', subtitle: 'SIMT execution units', view: 'sm', color: '#9ed75e', description: 'General arithmetic and integer/address work execute through the SM\'s functional units. CUDA threads and warps are software execution units, not a one-to-one map to the marketed CUDA-core count.', facts: [['Example operations', 'Arithmetic, addresses, reduction, stencil'], ['FP32 example', 'SIMT matrix multiply-accumulate'], ['Scheduling', 'Instructions issued from resident warps']], boundary: 'The green blocks are illustrative functional units. Their count and animation are not a throughput, utilization, or CUDA-core-count claim.', source: SOURCES.model },
  { id: 'tensor', name: 'Tensor MMA', subtitle: 'Matrix multiply-accumulate', view: 'sm', color: '#e9c576', description: 'Tensor Cores accelerate supported matrix instructions. In this explicit example, TF32, FP16, and INT8 matrix workloads select an MMA path. Changing a data type alone does not automatically move arbitrary CUDA code onto Tensor Cores.', facts: [['Ada generation', 'Fourth-generation Tensor Cores'], ['Floating example', 'TF32 / FP16 inputs, FP32 accumulation'], ['Integer example', 'INT8 inputs, INT32 accumulation']], boundary: 'Kernel/library selection, layout, dimensions, data types, and architecture govern actual support and performance. No fixed precision speedup is assigned.', source: SOURCES.ada },
  { id: 'rt', name: 'RT Core context', subtitle: 'RTX ray traversal / intersection', view: 'sm', color: '#dd93b2', description: 'RTX hardware separates ray traversal/intersection, general shading, and neural operations. RT Cores are specialized resources used through supported rendering/ray-tracing APIs; they are not generic acceleration for a CUDA reduction or matrix kernel.', facts: [['RT work', 'Ray traversal and intersection'], ['Shading', 'General programmable execution'], ['AI rendering', 'Tensor resources / supported neural workflows']], boundary: 'RT activity remains off for every CUDA workload in this app. The RTX reference page covers multiple newer architectures; this city\'s numeric bounds are specifically Ada.', source: SOURCES.rtx },
]

export const TOUR: DistrictId[] = ['host', 'dispatch', 'dram', 'l2', 'sm', 'scheduler', 'registers', 'shared', 'cuda', 'tensor', 'rt']